# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10
      - image: cockroachdb/cockroach:v2.0.4
        command: "start --insecure"
  
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/kumekay/kuhomon-server

    environment:
      TEST_RESULTS: /tmp/test-results
      CC_TEST_REPORTER_ID: 4ba7f3b15514d952353380c87329b918acf88527c73d4c177747a0fed40b153c

    steps:
      - checkout
      
      - run: mkdir -p $TEST_RESULTS

      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      
      - run: chmod +x ./cc-test-reporter
      
      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Waiting for CockroachDB to be ready
          command: |
            for i in `seq 1 60`;
            do
              nc -z localhost 26257 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Cockroach && exit 1

      - run: 
          name: 'Setup cockroach CLI'
          command: "wget -qO- https://binaries.cockroachdb.com/cockroach-v2.0.4.linux-amd64.tgz | tar xvz"
 
      - run: ./cockroach-v2.0.4.linux-amd64/cockroach sql --insecure -e 'CREATE DATABASE kuhomon_test'

      - run: 
          name: Run tests
          environment:
            DB_URL: "postgresql://root@localhost:26257/kuhomon_test?sslmode=disable"
          command: |
            ./cc-test-reporter before-build
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make cover | tee ${TEST_RESULTS}/go-test.out
            ./cc-test-reporter after-build --exit-code $?
      
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results